package hive;

public enum HiveExceptionCode {
	NULL_PIECE,
	NULL_PIECES,
	EMPTY_PIECES,
	NULL_END_COORDINATES,
	NULL_PLAYER,
	NOT_AVAILABLE_PUT,
	NOT_AVAILABLE_MOVE,
	PIECE_DOESNT_EXIST,
	PLAYER_DOESNT_EXIST,
	NOT_THIS_PLAYER_TURN,
	NOT_NULL_PIECE_COORDINATES,
	PIECE_NOT_ON_BOARD,
	NULL_COORDINATES
}
